version: "3"

volumes:
  node_modules:
services:
  fake-blog-nuxt-app-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "5001:5001"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules