name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v1

      - name: Stop docker
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: docker compose -f /home/${{ secrets.USERNAME }}/fake-blog-nuxt/docker-compose.yml down --remove-orphans

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: "."
          target: "/home/${{ secrets.USERNAME }}/fake-blog-nuxt"
          # strip_components: 1
          #          rm: true
          # overwrite: true

      - name: Start docker
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: docker compose -f /home/${{ secrets.USERNAME }}/fake-blog-nuxt/docker-compose.yml up -d
